model_name_or_path: WhereIsAI/UAE-Large-V1
train_split_name: train
valid_name_or_path: mteb/stsbenchmark-sts
valid_split_name: train
save_dir: ./train_result/uae_default_para/uae_ese
seed: -1
workers: 16

# configure Aoe
cosine_w: 1.0
ibn_w: 1.0
angle_w: 1.0
cosine_tau: 20.0
ibn_tau: 20.0
angle_tau: 20.0

# configure lora
apply_lora: 0
lora_r: 32
lora_alpha: 32
lora_dropout: 0.1

# configure training
learning_rate: 5e-5
warmup_steps: 100
logging_steps: 100
pooling_strategy: cls
epochs: 10
save_steps: 1000
batch_size: 32
maxlen: 512

# configure LLM
is_llm: 0
apply_billm: 0

# configure ESE
apply_ese: 1
ese_compression_size: 128
ese_kl_temperature: 1.0


